# Generated by Django 3.2.5 on 2022-04-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20, verbose_name='vehicle_model')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(verbose_name='ServiceTicket Date')),
                ('cost', models.IntegerField(default=0)),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.vehicle')),
            ],
        ),
    ]
