# Generated by Django 3.2.5 on 2022-04-26 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='service_date',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='item_serviced',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(default='', max_length=30, verbose_name='Operation status'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='', max_length=30, verbose_name='Plate number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='', max_length=30, verbose_name='Operation status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=30, verbose_name='vehicle_model'),
        ),
    ]
