# Generated by Django 3.2.5 on 2022-05-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestion_vehicle'),
        ('kyc', '0001_initial'),
        ('repair', '0007_auto_20220525_1141'),
        ('service', '0005_rename_service_ticket_serviceticket_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.vehicle'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
