# Generated by Django 3.2.5 on 2022-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_ticket_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ref',
            field=models.CharField(default='~2{Aljd%gF', max_length=50, verbose_name='Reference'),
        ),
    ]
