# Generated by Django 3.2.5 on 2022-05-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_ticket_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ref',
            field=models.CharField(default='\\v)a`%/XN-', max_length=50, verbose_name='Reference'),
        ),
    ]
